const DEFAULT_CASE_IDS = ["case_$(lpad(string(idx), 3, "0"))" for idx in 1:12]
const DEFAULT_OUTPUT_PATH =
    joinpath(@__DIR__, "..", "test", "fixtures", "toricbuilder_cache_q_blocks.jl")

module ToricBuilderExampleHelper
include(
    joinpath(@__DIR__, "..", "example", "toric_decoupling", "try_column_block_decoupling.jl")
)
end

function _parse_args(args)
    case_ids = DEFAULT_CASE_IDS
    output_path = DEFAULT_OUTPUT_PATH
    toricbuilder_dir = nothing
    cache_dir = nothing

    for arg in args
        if startswith(arg, "--case=")
            raw = split(arg[length("--case=")+1:end], ",")
            case_ids = [strip(case_id) for case_id in raw if !isempty(strip(case_id))]
        elseif startswith(arg, "--output=")
            output_path = arg[length("--output=")+1:end]
        elseif startswith(arg, "--toricbuilder-dir=")
            toricbuilder_dir = arg[length("--toricbuilder-dir=")+1:end]
        elseif startswith(arg, "--cache-dir=")
            cache_dir = arg[length("--cache-dir=")+1:end]
        else
            throw(ArgumentError("unsupported argument: $(arg)"))
        end
    end

    isempty(case_ids) && throw(ArgumentError("--case must name at least one case"))
    return (; case_ids, output_path, toricbuilder_dir, cache_dir)
end

function _load_toricbuilder_modules(options)
    helper = ToricBuilderExampleHelper
    toricbuilder_dir =
        options.toricbuilder_dir === nothing ? helper.default_toricbuilder_dir() : options.toricbuilder_dir
    cache_dir =
        options.cache_dir === nothing ? helper.default_cache_dir(toricbuilder_dir) : options.cache_dir
    modules = helper._load_optional_modules(toricbuilder_dir)
    modules.status == "PASS" ||
        throw(ArgumentError("could not load local ToricBuilder modules from $(toricbuilder_dir)"))
    return (; modules, toricbuilder_dir, cache_dir)
end

function _q_block_from_cache(case_id::AbstractString, modules, cache_dir::AbstractString)
    helper = ToricBuilderExampleHelper
    loaded = helper._load_cache_case(case_id, modules.ToricBuilder, cache_dir)
    loaded.status == "PASS" ||
        throw(ArgumentError("could not load ToricBuilder cache case $(case_id) from $(cache_dir)"))
    cache = loaded.case
    helper._cache_case_unusable(cache) &&
        throw(ArgumentError("ToricBuilder cache case $(case_id) does not contain a usable transfer_result"))

    transfer = cache.transfer_result
    hasproperty(transfer, :Q_size) ||
        throw(ArgumentError("ToricBuilder cache case $(case_id) transfer_result missing Q_size"))
    qsize = transfer.Q_size[1] ÷ 2
    source = transfer.column_transformation
    Q = helper._matrix_slice(source, 1:qsize, 1:qsize, modules)
    return (; matrix = Q, matrix_size = (qsize, qsize), source_size = Base.invokelatest(size, source))
end

function _sparse_entries(A)
    entries = Tuple{Int, Int, String}[]
    matrix_size = Base.invokelatest(size, A)
    for row in 1:matrix_size[1], col in 1:matrix_size[2]
        value = Base.invokelatest(getindex, A, row, col)
        Base.invokelatest(iszero, value) && continue
        push!(entries, (row, col, Base.invokelatest(string, value)))
    end
    return entries
end

function _display_source_path(path::AbstractString)
    normalized = replace(normpath(path), '\\' => '/')
    anchor = "topological-code-decoupling/julia_code/ToricBuilder"
    range = findfirst(anchor, normalized)
    return range === nothing ? normalized : normalized[first(range):end]
end

function _write_fixture(io, exported_cases, toricbuilder_dir::AbstractString, cache_dir::AbstractString)
    toricbuilder_source = _display_source_path(toricbuilder_dir)
    cache_source = _display_source_path(cache_dir)

    println(io, "# This file is generated by scripts/export_toricbuilder_cache_q_blocks.jl.")
    println(io, "# Do not edit the sparse entries by hand; refresh them from the local ToricBuilder cache.")
    println(io)
    println(io, "module ToricBuilderCacheQBlocks")
    println(io)
    println(io, "using Oscar")
    println(io, "using Suslin")
    println(io)
    println(io, "function _integer_exponent(ex)")
    println(io, "    ex isa Integer && return Int(ex)")
    println(io, "    if ex isa Expr && ex.head == :call && ex.args[1] == :- && length(ex.args) == 2 && ex.args[2] isa Integer")
    println(io, "        return -Int(ex.args[2])")
    println(io, "    end")
    println(io, "    throw(ArgumentError(\"unsupported Laurent exponent expression: \$(ex)\"))")
    println(io, "end")
    println(io)
    println(io, "function _eval_laurent_expr(ex, R, variables)")
    println(io, "    if ex isa Integer")
    println(io, "        return ex == 0 ? zero(R) : ex == 1 ? one(R) : R(ex)")
    println(io, "    elseif ex isa Symbol")
    println(io, "        haskey(variables, ex) || throw(ArgumentError(\"unknown Laurent variable: \$(ex)\"))")
    println(io, "        return variables[ex]")
    println(io, "    elseif ex isa Expr && ex.head == :call")
    println(io, "        op = ex.args[1]")
    println(io, "        if op == :+")
    println(io, "            value = zero(R)")
    println(io, "            for arg in ex.args[2:end]")
    println(io, "                value += _eval_laurent_expr(arg, R, variables)")
    println(io, "            end")
    println(io, "            return value")
    println(io, "        elseif op == :*")
    println(io, "            value = one(R)")
    println(io, "            for arg in ex.args[2:end]")
    println(io, "                value *= _eval_laurent_expr(arg, R, variables)")
    println(io, "            end")
    println(io, "            return value")
    println(io, "        elseif op == :^ && length(ex.args) == 3")
    println(io, "            return _eval_laurent_expr(ex.args[2], R, variables)^_integer_exponent(ex.args[3])")
    println(io, "        elseif op == :- && length(ex.args) == 2")
    println(io, "            return -_eval_laurent_expr(ex.args[2], R, variables)")
    println(io, "        end")
    println(io, "    end")
    println(io, "    throw(ArgumentError(\"unsupported Laurent expression: \$(ex)\"))")
    println(io, "end")
    println(io)
    println(io, "function _parse_laurent_value(R, u, v, value::AbstractString)")
    println(io, "    return _eval_laurent_expr(Meta.parse(value), R, Dict(:u => u, :v => v))")
    println(io, "end")
    println(io)
    println(io, "function materialize_sparse_entries(entry)")
    println(io, "    R, (u, v) = Suslin.suslin_laurent_polynomial_ring(GF(2), [\"u\", \"v\"])")
    println(io, "    return [(row, col, _parse_laurent_value(R, u, v, value)) for (row, col, value) in entry.sparse_entries]")
    println(io, "end")
    println(io)
    println(io, "function _sparse_laurent_matrix(R, u, v, rows::Int, cols::Int, entries)")
    println(io, "    M = zero_matrix(R, rows, cols)")
    println(io, "    for (row, col, value) in entries")
    println(io, "        M[row, col] = _parse_laurent_value(R, u, v, value)")
    println(io, "    end")
    println(io, "    return M")
    println(io, "end")
    println(io)
    println(io, "function materialize_matrix(entry)")
    println(io, "    R, (u, v) = Suslin.suslin_laurent_polynomial_ring(GF(2), [\"u\", \"v\"])")
    println(io, "    return _sparse_laurent_matrix(R, u, v, entry.dimensions.matrix[1], entry.dimensions.matrix[2], entry.sparse_entries)")
    println(io, "end")
    println(io)
    println(io, "function _entry(case_id::String, source_cache_file::String, matrix_size, source_size, entries)")
    println(io, "    return (;")
    println(io, "        id = case_id,")
    println(io, "        kind = :toricbuilder_cache_column_q_block,")
    println(io, "        source_cache_file,")
    println(io, "        source_block = :column_transformation_upper_left_q_block,")
    println(io, "        ring = (;")
    println(io, "            description = \"GF(2)[u^+/-1, v^+/-1]\",")
    println(io, "            base_field = \"GF(2)\",")
    println(io, "            variables = (\"u\", \"v\"),")
    println(io, "            kind = \"multivariate Laurent polynomial ring\",")
    println(io, "        ),")
    println(io, "        dimensions = (;")
    println(io, "            matrix = matrix_size,")
    println(io, "            column_transformation = source_size,")
    println(io, "        ),")
    println(io, "        storage_format = :sparse_coordinate_entries,")
    println(io, "        value_format = :julia_laurent_expression_string,")
    println(io, "        sparse_entry_count = length(entries),")
    println(io, "        sparse_entries = entries,")
    println(io, "        matrix = (; storage = :lazy_sparse_coordinate_entries, materializer = :materialize_matrix),")
    println(io, "        expected_test_level = matrix_size[1] >= 100 ? :optional_slow : :default_contract,")
    println(io, "        expected_current_status = case_id == \"case_001\" ? :original_gl_boundary : :unknown_pending_audit,")
    println(io, "        provenance = (;")
    println(io, "            toricbuilder_path = $(repr(toricbuilder_source)),")
    println(io, "            toricbuilder_cache_dir = $(repr(cache_source)),")
    println(io, "            source_field = \"transfer_result.column_transformation\",")
    println(io, "            extraction_rule = \"upper-left Q_size[1] ÷ 2 square block\",")
    println(io, "        ),")
    println(io, "    )")
    println(io, "end")
    println(io)
    println(io, "function catalog()")
    println(io, "    return (;")
    println(io, "        cases = [")

    for exported in exported_cases
        source_file = string(exported.case_id, ".jls")
        println(io, "            _entry(")
        println(io, "                $(repr(exported.case_id)),")
        println(io, "                $(repr(source_file)),")
        println(io, "                $(exported.matrix_size),")
        println(io, "                $(exported.source_size),")
        println(io, "                [")
        for (row, col, value) in exported.entries
            println(io, "                    ($(row), $(col), $(repr(value))),")
        end
        println(io, "                ],")
        println(io, "            ),")
    end

    println(io, "        ],")
    println(io, "    )")
    println(io, "end")
    println(io)
    println(io, "end")
end

function main(args = ARGS)
    options = _parse_args(args)
    loaded = _load_toricbuilder_modules(options)
    exported_cases = []
    for case_id in options.case_ids
        block = _q_block_from_cache(case_id, loaded.modules, loaded.cache_dir)
        push!(
            exported_cases,
            (;
                case_id,
                matrix_size = block.matrix_size,
                source_size = block.source_size,
                entries = _sparse_entries(block.matrix),
            ),
        )
    end

    mkpath(dirname(options.output_path))
    open(options.output_path, "w") do io
        _write_fixture(io, exported_cases, loaded.toricbuilder_dir, loaded.cache_dir)
    end
    println("wrote $(length(exported_cases)) ToricBuilder Q-block fixtures to $(options.output_path)")
    return options.output_path
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
